import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/common/header'
import { Footer } from '@/components/common/footer'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: '400',
})

const CirularStd = localFont({
  src: './fonts/CircularStd-BoldItalic.woff',
  variable: '--font-CircularStd-sans',
  weight: '100',
})

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={` ${inter.variable} ${roboto.variable} ${CirularStd.variable}   antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
